[viewport]
maximum_width = 26

[netres]
limit = 25.0

[game]
map_pool = "LPPMapPool"
soft_max_players = "111"
lobbyenabled = true
panic_bunker.min_account_age = 1440
#panic_bunker.min_overall_hours = 0

[server]
rules_file = "LPPRuleset"

[ic]
flavor_text = true
flavor_text_length = 1024

[rules]
time = 60.0

[infolinks]
discord = "https://wiki.legacyofparadise.space/discord"
github = "https://github.com/Legacy-Of-Paradise/main-erp"
wiki = "http://wiki.legacyofparadise.space/"
website = "https://boosty.to/legacy-of-paradise"
appeal = "https://wiki.legacyofparadise.space/discord"

[votekick]
enabled = false

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
autovote_enabled = true
map_enabled = true
preset_enabled = true
restart_enabled = true

[interaction]
rate_limit_announce_admins_delay = -1

[hub]
advertise = true
tags = "18+,lang:ru,region:eu_e,rp:med"

[shuttle]
auto_call_time = 90
arrivals = true
arrivals_map = "/Maps/_NewParadise/Misc/paradise_terminal.yml"
arrivals_planet = false
emergency_early_launch_allowed = true

[admin]
admins_count_in_playercount = true
see_own_notes = true

[ahelp]
admin_prefix = true
rate_limit_count = 2
rate_limit_period = 10
admin_prefix_webhook = true

[discord]
rich_main_icon_id = "https://bit.ly/lopicon"

[supermatter]
rads_base = 1
